name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    environment: preview
    env:
      PULL_REQUEST: ${{ github.event.number }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
      ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Get branch expiration date (2 weeks from now)
        run: echo "EXPIRES_AT=$(date -u --date '+14 days' +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Create Neon Branch
        id: create_neon_branch
        continue-on-error: true
        uses: neondatabase/create-branch-action@v6
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          expires_at: ${{ env.EXPIRES_AT }}

      - name: Reset Neon Branch to parent
        id: reset_neon_branch
        uses: neondatabase/reset-branch-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          parent: true
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Set DATABASE_URL
        run: |
          echo "DATABASE_URL=${{ steps.reset_neon_branch.outputs.db_url_with_pooler }}" >> "$GITHUB_ENV"
          echo "NEON_BRANCH_ID=${{ steps.reset_neon_branch.outputs.branch_id }}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          stage: preview-${{ github.head_ref }}
